# These are the available config settings.

keyword: ["@todo", "TODO:"]     # string|string[]
bodyKeyword: ["@body", "BODY:"] # string|string[]
autoAssign: CorrM               # string|string[]|boolean
